PRAGMA foreign_keys = ON;

-- Dynamic permission catalog source for Web/APK administration.
-- permission_id is stable implementation identity; resource_code/action_code remain the public authorization vocabulary.
INSERT OR IGNORE INTO auth_permissions(permission_id, resource_code, action_code, description, status) VALUES
  ('PERM:employee:view', 'employee', 'view', 'Xem nhân sự', 'ACTIVE'),
  ('PERM:employee:create', 'employee', 'create', 'Tạo nhân sự', 'ACTIVE'),
  ('PERM:employee:edit', 'employee', 'edit', 'Sửa nhân sự', 'ACTIVE'),
  ('PERM:employee:status', 'employee', 'status', 'Đổi trạng thái nhân sự', 'ACTIVE'),
  ('PERM:employee:portrait', 'employee', 'portrait', 'Đổi ảnh nhân sự', 'ACTIVE'),
  ('PERM:attendance:scan', 'attendance', 'scan', 'Quét VÀO/RA', 'ACTIVE'),
  ('PERM:attendance:correct', 'attendance', 'correct', 'Điều chỉnh VÀO/RA', 'ACTIVE'),
  ('PERM:session:open', 'session', 'open', 'Mở phiên làm việc', 'ACTIVE'),
  ('PERM:session:close', 'session', 'close', 'Đóng phiên làm việc', 'ACTIVE'),
  ('PERM:session.extra:approve', 'session.extra', 'approve', 'Duyệt phiên bổ sung', 'ACTIVE'),
  ('PERM:task.pick:operate', 'task.pick', 'operate', 'Thao tác PICK', 'ACTIVE'),
  ('PERM:task.pack:operate', 'task.pack', 'operate', 'Thao tác PACK', 'ACTIVE'),
  ('PERM:resource:view', 'resource', 'view', 'Xem tài nguyên', 'ACTIVE'),
  ('PERM:resource:assign', 'resource', 'assign', 'Cấp tài nguyên', 'ACTIVE'),
  ('PERM:resource:release', 'resource', 'release', 'Trả tài nguyên', 'ACTIVE'),
  ('PERM:resource:change', 'resource', 'change', 'Đổi tài nguyên', 'ACTIVE'),
  ('PERM:resource:reissue', 'resource', 'reissue', 'Phát lại tài nguyên', 'ACTIVE'),
  ('PERM:resource.borrow:request', 'resource.borrow', 'request', 'Yêu cầu mượn tài nguyên chéo cụm', 'ACTIVE'),
  ('PERM:resource.borrow:approve', 'resource.borrow', 'approve', 'Duyệt mượn tài nguyên chéo cụm', 'ACTIVE'),
  ('PERM:pack.mapping:manage', 'pack.mapping', 'manage', 'Quản lý mapping Bàn Pack - User Pack', 'ACTIVE'),
  ('PERM:labor:view', 'labor', 'view', 'Xem Công nhật', 'ACTIVE'),
  ('PERM:labor:start_finish', 'labor', 'start_finish', 'Start/Finish Công nhật', 'ACTIVE'),
  ('PERM:labor:correct', 'labor', 'correct', 'Điều chỉnh Công nhật', 'ACTIVE'),
  ('PERM:labor.catalog:manage', 'labor.catalog', 'manage', 'Quản lý danh mục Công nhật', 'ACTIVE'),
  ('PERM:dropped_goods:create', 'dropped_goods', 'create', 'Ghi nhận hàng rớt', 'ACTIVE'),
  ('PERM:dropped_goods:view', 'dropped_goods', 'view', 'Xem hàng rớt', 'ACTIVE'),
  ('PERM:document:create', 'document', 'create', 'Tạo biên bản/tài liệu', 'ACTIVE'),
  ('PERM:document:finalize', 'document', 'finalize', 'Chốt biên bản/tài liệu', 'ACTIVE'),
  ('PERM:document:view', 'document', 'view', 'Xem tài liệu/ảnh', 'ACTIVE'),
  ('PERM:account:manage', 'account', 'manage', 'Quản lý tài khoản', 'ACTIVE'),
  ('PERM:permission:manage', 'permission', 'manage', 'Phân quyền', 'ACTIVE'),
  ('PERM:conflict:resolve', 'conflict', 'resolve', 'Xử lý xung đột nghiệp vụ', 'ACTIVE'),
  ('PERM:history:view', 'history', 'view', 'Xem lịch sử', 'ACTIVE'),
  ('PERM:projection:admin', 'projection', 'admin', 'Quản lý trạng thái đồng bộ Google', 'ACTIVE'),
  ('PERM:import:run', 'import', 'run', 'Nhập dữ liệu', 'ACTIVE'),
  ('PERM:export:run', 'export', 'run', 'Xuất dữ liệu', 'ACTIVE'),
  ('PERM:system.settings:manage', 'system.settings', 'manage', 'Cài đặt cụm/tính năng', 'ACTIVE'),
  ('PERM:lan.routing:force', 'lan.routing', 'force', 'Chủ động ép tuyến LAN khi Cloud đang khỏe', 'ACTIVE');
